# Generated by Django 5.2.4 on 2025-07-22 20:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0018_add_smiles_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_submissions_enabled', models.BooleanField(default=True, help_text='Allow users to submit public research snippets')),
                ('require_review_flair', models.BooleanField(default=True, help_text="Show 'Needs Review' badges on unverified snippets")),
                ('higher_confirmation_rate', models.BooleanField(default=False, help_text='Require more votes for popular/trending snippets')),
                ('ai_summaries_enabled', models.BooleanField(default=True, help_text='Enable AI-powered summarization features')),
                ('min_votes_for_flair', models.IntegerField(default=1, help_text='Minimum votes before showing review flair')),
                ('verification_threshold', models.IntegerField(default=3, help_text='Minimum positive votes for verification')),
                ('flagging_threshold', models.IntegerField(default=2, help_text='Minimum rejection votes for flagging')),
                ('high_confidence_threshold', models.IntegerField(default=5, help_text='Votes needed for high-confidence validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Settings',
                'verbose_name_plural': 'Research Settings',
            },
        ),
        migrations.CreateModel(
            name='SnippetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for tag display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snippet Tag',
                'verbose_name_plural': 'Snippet Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title describing the research snippet', max_length=300)),
                ('content', models.TextField(help_text='The main research content or findings')),
                ('snippet_type', models.CharField(choices=[('general', 'General Research'), ('mechanism', 'Mechanism of Action'), ('pharmacology', 'Pharmacology'), ('safety', 'Safety Data'), ('clinical', 'Clinical Studies'), ('dosage', 'Dosage Information'), ('interaction', 'Drug Interactions'), ('experience', 'User Experience'), ('other', 'Other')], default='general', help_text='Category of research', max_length=50)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('public_review', 'Public + Review Required')], default='private', help_text='Who can see this snippet', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('needs_review', 'Needs Review'), ('verified', 'Verified'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='draft', help_text='Review status of the snippet', max_length=20)),
                ('source_title', models.CharField(blank=True, help_text='Title of the research paper, study, or source', max_length=500)),
                ('source_url', models.URLField(blank=True, help_text='Link to the original source (PubMed, journal, etc.)')),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier (DOI) if available', max_length=100)),
                ('pubmed_id', models.CharField(blank=True, help_text='PubMed ID if available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of the content')),
                ('ai_generated', models.BooleanField(default=False, help_text='Whether this snippet was generated by AI')),
                ('confidence_score', models.IntegerField(blank=True, help_text="Submitter's confidence in the accuracy (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('compound', models.ForeignKey(help_text='Which compound this research relates to', on_delete=django.db.models.deletion.CASCADE, related_name='research_snippets', to='compounds.compound')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Snippet',
                'verbose_name_plural': 'Research Snippets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SnippetTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchsnippet')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.snippettag')),
                ('tagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snippet Tagging',
                'verbose_name_plural': 'Snippet Taggings',
                'unique_together': {('snippet', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='researchsnippet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='snippets', through='research.SnippetTagging', to='research.snippettag'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('authenticated', 'Authenticated User'), ('trusted_reviewer', 'Trusted Reviewer'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='authenticated', max_length=20)),
                ('vote_weight', models.FloatField(default=1.0, help_text="Weight multiplier for this user's votes")),
                ('can_moderate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.CreateModel(
            name='SnippetReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('validate', 'Validate ✔️'), ('reject', 'Reject ❌')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Optional feedback on the snippet quality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_reviews', to=settings.AUTH_USER_MODEL)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='research.researchsnippet')),
            ],
            options={
                'verbose_name': 'Snippet Review',
                'verbose_name_plural': 'Snippet Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('snippet', 'reviewer')},
            },
        ),
    ]
