# Generated by Django 5.2.4 on 2025-07-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_remove_pubmed_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchsnippet',
            name='confidence_score',
        ),
        migrations.AlterField(
            model_name='researchsnippet',
            name='visibility',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], default='public', help_text='Snippet visibility - all snippets are public unless saved as draft', max_length=20),
        ),
    ]
