# Generated by Django 5.2.4 on 2026-02-06 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0030_compoundmolpropprediction'),
        ('research', '0004_snippetcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('max_results', models.PositiveIntegerField(default=20)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('query', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_import_jobs', to='compounds.compound')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_import_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Import Job',
                'verbose_name_plural': 'Research Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
