# Generated by Django 5.2.4 on 2025-07-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Compound Category',
                'verbose_name_plural': 'Compound Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompoundMechanismOfAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Compound Mechanism of Action',
                'verbose_name_plural': 'Compound Mechanisms of Action',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('aliases', models.CharField(blank=True, help_text='Comma-saparated alternative names or acronyms.', max_length=255)),
                ('categories', models.ManyToManyField(blank=True, related_name='compounds', to='compounds.compoundcategories')),
                ('mechanism_of_action', models.ManyToManyField(blank=True, related_name='compounds', to='compounds.compoundmechanismofaction')),
            ],
        ),
    ]
