# Generated by Django 5.2.4 on 2025-07-19 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundReceptorTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Compound Receptor Target',
                'verbose_name_plural': 'Compound Receptor Targets',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='compound',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='receptor_targets',
            field=models.ManyToManyField(blank=True, related_name='compounds', to='compounds.compoundreceptortargets'),
        ),
        migrations.CreateModel(
            name='CompoundRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate compound based on likelihood of recommending. (1 to 5)')),
                ('comment', models.TextField(blank=True, help_text='Describe experience (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='compounds.compound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('compound', 'user')},
            },
        ),
    ]
