# Generated by Django 5.2.4 on 2025-07-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_compoundreceptortargets_compound_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundSafetyScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liver_toxicity', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_screening', to='compounds.compound', unique=True)),
            ],
        ),
    ]
