# Generated by Django 5.2.4 on 2025-07-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0003_compoundsafetyscreening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundsafetyscreening',
            name='compound',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_screening', to='compounds.compound'),
        ),
    ]
