# Generated by Django 5.2.4 on 2025-07-19 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0004_alter_compoundsafetyscreening_compound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compoundsafetyscreening',
            options={'ordering': ['-created_at'], 'verbose_name': 'Compound Safety Screening'},
        ),
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='cardiovascular_risk',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = No risk observed; 5 = Lethal risk', null=True),
        ),
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='confidence_score',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], help_text='How confident are you in the data provided?', null=True),
        ),
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='hpta_suppression',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = No suppression observed; 5 = Full suppression', null=True),
        ),
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='kidney_toxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='neurotoxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='reference_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='compoundsafetyscreening',
            name='liver_toxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
    ]
