# Generated by Django 5.2.4 on 2025-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0005_alter_compoundsafetyscreening_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='bladder_toxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='lung_toxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
        migrations.AddField(
            model_name='compoundsafetyscreening',
            name='pancreas_toxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
    ]
