# Generated by Django 5.2.4 on 2025-07-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0006_compoundsafetyscreening_bladder_toxicity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this compound.', null=True, upload_to='compound_images/'),
        ),
    ]
