# Generated by Django 5.2.4 on 2025-07-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0007_compound_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='compound',
            name='receptor_targets',
        ),
        migrations.AddField(
            model_name='compoundreceptortargets',
            name='target_type',
            field=models.CharField(blank=True, choices=[('receptor', 'Receptor'), ('enzyme', 'Enzyme'), ('ion_channel', 'Ion Channel'), ('transporter', 'Transporter'), ('other', 'Other')], help_text='Type of target (e.g., receptor, enzyme, ion channel, transporter)', max_length=100),
        ),
        migrations.AddField(
            model_name='compound',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='compounds', to='compounds.Targets'),
        ),
    ]
