# Generated by Django 5.2.4 on 2025-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0008_compoundtargets_remove_compound_receptor_targets_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompoundReceptorTargets',
        ),
        migrations.AlterModelOptions(
            name='targets',
            options={'ordering': ['name'], 'verbose_name': 'Compound Receptor Target', 'verbose_name_plural': 'Compound Receptor Targets'},
        ),
        migrations.RemoveField(
            model_name='compound',
            name='targets',
        ),
        migrations.AddField(
            model_name='targets',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='targets',
            name='target_type',
            field=models.CharField(blank=True, choices=[('receptor', 'Receptor'), ('enzyme', 'Enzyme'), ('ion_channel', 'Ion Channel'), ('transporter', 'Transporter'), ('other', 'Other')], help_text='Type of target (e.g., receptor, enzyme, ion channel, transporter)', max_length=100),
        ),
    ]
