# Generated by Django 5.2.4 on 2025-07-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0009_delete_compoundreceptortargets_alter_targets_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundTargetInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(blank=True, choices=[('agonist', 'Agonist'), ('antagonist', 'Antagonist'), ('partial_agonist', 'Partial Agonist'), ('inverse_agonist', 'Inverse Agonist'), ('pam', 'Positive Allosteric Modulator'), ('nam', 'Negative Allosteric Modulator'), ('binder', 'Binder'), ('inhibitor', 'Inhibitor'), ('activator', 'Activator'), ('unknown', 'Unknown')], help_text='Type of interaction with the target (e.g., agonist, antagonist, etc.)', max_length=50)),
                ('affinity', models.FloatField(blank=True, help_text='Binding affinity (e.g., Ki, IC50) in nM or pM', null=True)),
                ('affinity_unit', models.CharField(blank=True, help_text='Unit of the affinity (e.g., nM, pM)', max_length=10)),
                ('affinity_type', models.CharField(blank=True, help_text='Type of affinity measurement (e.g., Ki, IC50)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the interaction')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_interactions', to='compounds.compound')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_interactions', to='compounds.targets')),
            ],
            options={
                'verbose_name': 'Compound Target Interaction',
                'verbose_name_plural': 'Compound Target Interactions',
                'ordering': ['compound__name', 'target__name'],
                'unique_together': {('compound', 'target', 'interaction_type')},
            },
        ),
    ]
