# Generated by Django 5.2.4 on 2025-07-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0010_compoundtargetinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundmechanismofaction',
            name='target_interaction',
            field=models.CharField(blank=True, choices=[('agonist', 'Agonist'), ('antagonist', 'Antagonist'), ('partial_agonist', 'Partial Agonist'), ('inverse_agonist', 'Inverse Agonist'), ('pam', 'Positive Allosteric Modulator'), ('nam', 'Negative Allosteric Modulator'), ('binder', 'Binder'), ('inhibitor', 'Inhibitor'), ('activator', 'Activator'), ('unknown', 'Unknown')], help_text='Type of interaction with the target (e.g., agonist, antagonist, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='compoundmechanismofaction',
            name='target_name',
            field=models.CharField(blank=True, help_text='Name of the target (e.g., receptor, enzyme, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='compoundmechanismofaction',
            name='target_type',
            field=models.CharField(blank=True, choices=[('receptor', 'Receptor'), ('enzyme', 'Enzyme'), ('ion_channel', 'Ion Channel'), ('transporter', 'Transporter'), ('other', 'Other')], help_text='Type of target (e.g., receptor, enzyme, ion channel, transporter)', max_length=100),
        ),
    ]
