# Generated by Django 5.2.4 on 2025-07-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0011_compoundmechanismofaction_target_interaction_and_more'),
    ]

    operations = [
    ]
