# Generated by Django 5.2.4 on 2025-07-22 16:01

from django.db import migrations, connection


def delete_tables_if_exist(apps, schema_editor):
    """Safely delete tables if they exist"""
    cursor = connection.cursor()
    
    # Check what tables exist
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
    existing_tables = [row[0] for row in cursor.fetchall()]
    
    # Drop tables if they exist
    tables_to_drop = [
        'compounds_compoundtargetinteraction',
        'compounds_targets',
        'compounds_compoundtargets'  # Alternative name that might exist
    ]
    
    for table in tables_to_drop:
        if table in existing_tables:
            cursor.execute(f'DROP TABLE IF EXISTS {table}')


def reverse_delete_tables(apps, schema_editor):
    """This is irreversible - we can't recreate the deleted tables"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0012_auto_20250722_1548'),
    ]

    operations = [
        migrations.RunPython(delete_tables_if_exist, reverse_delete_tables),
    ]
