# Generated by Django 5.2.4 on 2025-07-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0015_populate_and_swap_target_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompoundTargetInteraction',
        ),
        migrations.DeleteModel(
            name='Targets',
        ),
    ]
