# Generated by Django 5.2.4 on 2025-07-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0015_populate_and_swap_target_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS compounds_compoundtargetinteraction;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS compounds_targets;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(name='CompoundTargetInteraction'),
                migrations.DeleteModel(name='Targets'),
            ],
        ),
    ]
