# Generated by Django 5.2.4 on 2025-07-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0016_delete_compoundtargetinteraction_delete_targets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compoundmechanismofaction',
            options={'ordering': ['target_name'], 'verbose_name': 'Compound Mechanism of Action', 'verbose_name_plural': 'Compound Mechanisms of Action'},
        ),
        migrations.RemoveField(
            model_name='compoundmechanismofaction',
            name='name',
        ),
    ]
