# Generated by Django 5.2.4 on 2025-07-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0017_alter_compoundmechanismofaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='smiles',
            field=models.CharField(blank=True, help_text='SMILES notation for molecular structure', max_length=1000),
        ),
    ]
