# Generated by Django 5.2.4 on 2025-07-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0018_add_smiles_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='image',
        ),
    ]
