# Generated by Django 5.2.4 on 2025-07-23 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0020_alter_compoundmechanismofaction_target_interaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset_minutes', models.PositiveIntegerField(help_text='Smallest time after intake before effects begin (minutes)')),
                ('peak_min_minutes', models.PositiveIntegerField(help_text='Smallest time to peak effects (minutes)')),
                ('peak_max_minutes', models.PositiveIntegerField(help_text='Largest time to peak effects (minutes)')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Total time of effects (minutes)')),
                ('half_life_minutes', models.PositiveIntegerField(blank=True, help_text='Optional half-life for decay visualization (minutes)', null=True)),
                ('effect_shape', models.CharField(choices=[('bell', 'Bell Curve'), ('ramp', 'Ramp Up'), ('flat-top', 'Flat Top'), ('custom', 'Custom')], default='bell', help_text='Preset curve profile shape', max_length=20)),
                ('notes', models.CharField(blank=True, help_text='Additional notes about this effect profile', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(help_text='Compound this effect profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='effect_windows', to='compounds.compound')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Effect Window',
                'verbose_name_plural': 'Effect Windows',
                'ordering': ['-created_at'],
            },
        ),
    ]
