# Generated by Django 5.2.4 on 2025-07-24 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0021_effectwindow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the target'),
        ),
        migrations.AddField(
            model_name='target',
            name='type',
            field=models.CharField(choices=[('receptor', 'Receptor'), ('enzyme', 'Enzyme'), ('ion_channel', 'Ion Channel'), ('transporter', 'Transporter'), ('protein', 'Protein'), ('other', 'Other')], default='receptor', help_text='Type of target (e.g., receptor, enzyme, ion channel, transporter)', max_length=100),
        ),
        migrations.CreateModel(
            name='CompoundTargetInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(choices=[('agonist', 'Agonist'), ('antagonist', 'Antagonist'), ('partial_agonist', 'Partial Agonist'), ('inverse_agonist', 'Inverse Agonist'), ('pam', 'Positive Allosteric Modulator'), ('nam', 'Negative Allosteric Modulator'), ('inhibitor', 'Inhibitor'), ('inducer', 'Inducer'), ('activator', 'Activator'), ('binder', 'Binder'), ('substrate', 'Substrate'), ('unknown', 'Unknown')], help_text='How the compound interacts with this target', max_length=50)),
                ('affinity_level', models.CharField(choices=[('very_high', 'Very High (nM)'), ('high', 'High (low μM)'), ('moderate', 'Moderate (μM)'), ('low', 'Low (high μM)'), ('very_low', 'Very Low (mM+)'), ('unknown', 'Unknown')], default='unknown', help_text='Binding affinity level', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this interaction')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_interactions', to='compounds.compound')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_interactions', to='compounds.target')),
            ],
            options={
                'verbose_name': 'Compound-Target Interaction',
                'verbose_name_plural': 'Compound-Target Interactions',
                'ordering': ['compound', 'target'],
                'unique_together': {('compound', 'target', 'mechanism')},
            },
        ),
        migrations.CreateModel(
            name='CompoundToCompoundTargetInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('synergistic', 'Synergistic'), ('antagonistic', 'Antagonistic'), ('competitive_metabolism', 'Competitive Metabolism'), ('enzyme_inhibition', 'Enzyme Inhibition'), ('enzyme_induction', 'Enzyme Induction'), ('receptor_competition', 'Receptor Competition'), ('additive', 'Additive'), ('unknown', 'Unknown')], help_text='Type of interaction between the compounds', max_length=50)),
                ('description', models.TextField(help_text="Detailed description of the interaction (e.g., 'Compound A inhibits CYP2D6, delaying metabolism of Compound B')")),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Confidence level of this interaction data', max_length=10)),
                ('source', models.CharField(blank=True, help_text='Source reference (PubMed ID, DOI, or URL)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound_a', models.ForeignKey(help_text='First compound in the interaction', on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_compound_a', to='compounds.compound')),
                ('compound_b', models.ForeignKey(help_text='Second compound in the interaction', on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_compound_b', to='compounds.compound')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(help_text='Shared target through which the interaction occurs', on_delete=django.db.models.deletion.CASCADE, related_name='compound_compound_interactions', to='compounds.target')),
            ],
            options={
                'verbose_name': 'Compound-to-Compound Interaction',
                'verbose_name_plural': 'Compound-to-Compound Interactions',
                'ordering': ['compound_a', 'compound_b', 'target'],
                'unique_together': {('compound_a', 'compound_b', 'target')},
            },
        ),
    ]
