# Generated by Django 5.2.4 on 2025-07-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0022_target_description_target_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='chembl_id',
            field=models.CharField(blank=True, help_text='ChEMBL compound ID (e.g., CHEMBL25)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='compoundtargetinteraction',
            name='source',
            field=models.CharField(blank=True, help_text='Data source (e.g., ChEMBL, PubMed, manual)', max_length=100),
        ),
        migrations.AddField(
            model_name='target',
            name='chembl_id',
            field=models.CharField(blank=True, help_text='ChEMBL target ID (e.g., CHEMBL2095189)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='target',
            name='organism',
            field=models.CharField(blank=True, help_text='Organism (e.g., Homo sapiens, Mus musculus)', max_length=255),
        ),
        migrations.AddField(
            model_name='target',
            name='target_type',
            field=models.CharField(choices=[('receptor', 'Receptor'), ('enzyme', 'Enzyme'), ('ion_channel', 'Ion Channel'), ('transporter', 'Transporter'), ('protein', 'Protein'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', help_text='Type of target (e.g., receptor, enzyme, ion channel, transporter)', max_length=100),
        ),
        migrations.AlterField(
            model_name='compoundtargetinteraction',
            name='affinity_level',
            field=models.CharField(choices=[('high', 'High (< 100 nM)'), ('medium', 'Medium (100-1000 nM)'), ('low', 'Low (> 1000 nM)'), ('very_high', 'Very High (< 10 nM)'), ('very_low', 'Very Low (> 10 μM)'), ('unknown', 'Unknown')], default='unknown', help_text='Binding affinity level', max_length=20),
        ),
        migrations.AlterField(
            model_name='compoundtargetinteraction',
            name='mechanism',
            field=models.CharField(choices=[('agonist', 'Agonist'), ('antagonist', 'Antagonist'), ('partial_agonist', 'Partial Agonist'), ('inverse_agonist', 'Inverse Agonist'), ('pam', 'Positive Allosteric Modulator'), ('nam', 'Negative Allosteric Modulator'), ('inhibitor', 'Inhibitor'), ('inducer', 'Inducer'), ('activator', 'Activator'), ('binder', 'Binder'), ('substrate', 'Substrate'), ('modulator', 'Modulator'), ('blocker', 'Blocker'), ('opener', 'Opener'), ('unknown', 'Unknown')], help_text='How the compound interacts with this target', max_length=50),
        ),
        migrations.AlterField(
            model_name='compoundtocompoundtargetinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('synergistic', 'Synergistic'), ('antagonistic', 'Antagonistic'), ('competitive', 'Competitive'), ('competitive_metabolism', 'Competitive Metabolism'), ('enzyme_inhibition', 'Enzyme Inhibition'), ('enzyme_induction', 'Enzyme Induction'), ('receptor_competition', 'Receptor Competition'), ('additive', 'Additive'), ('unknown', 'Unknown')], help_text='Type of interaction between the compounds', max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.CharField(choices=[('receptor', 'Receptor'), ('enzyme', 'Enzyme'), ('ion_channel', 'Ion Channel'), ('transporter', 'Transporter'), ('protein', 'Protein'), ('other', 'Other'), ('unknown', 'Unknown')], default='receptor', help_text='Type of target (deprecated, use target_type)', max_length=100),
        ),
    ]
