# Generated by Django 5.2.4 on 2025-07-24 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0023_add_chembl_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Action type (e.g., agonist, antagonist, inhibitor)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable display name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this action type')),
                ('category', models.CharField(blank=True, help_text='Broad category (e.g., activation, inhibition, modulation)', max_length=50)),
            ],
            options={
                'verbose_name': 'Action Type',
                'verbose_name_plural': 'Action Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Target type (e.g., receptor, enzyme, ion_channel)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable display name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this target type')),
                ('category', models.CharField(blank=True, help_text='Broad category (e.g., membrane, intracellular, secreted)', max_length=50)),
            ],
            options={
                'verbose_name': 'Target Type',
                'verbose_name_plural': 'Target Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='compoundtargetinteraction',
            name='structured_action_type',
            field=models.ForeignKey(blank=True, help_text='Structured action type reference', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounds.actiontype'),
        ),
        migrations.AddField(
            model_name='target',
            name='structured_target_type',
            field=models.ForeignKey(blank=True, help_text='Structured target type reference', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounds.targettype'),
        ),
    ]
