# Generated by Django 5.2.4 on 2025-07-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0024_actiontype_targettype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this compound page has been viewed'),
        ),
    ]
