# Generated by Django 5.2.4 on 2025-07-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0025_add_compound_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='ensembl_id',
            field=models.CharField(blank=True, help_text='Ensembl protein ID for pathway mapping (e.g., ENSP00000123456)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='gene_name',
            field=models.CharField(blank=True, help_text='Gene name/symbol (e.g., HTR2A, DRD2)', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='uniprot_id',
            field=models.CharField(blank=True, help_text='UniProt protein ID for pathway mapping (e.g., P14416)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TargetPathwayInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactome_id', models.CharField(help_text='Reactome pathway ID (e.g., R-HSA-112314)', max_length=255)),
                ('pathway_name', models.CharField(help_text='Name of the biological pathway', max_length=512)),
                ('pathway_type', models.CharField(blank=True, help_text='Type/category of pathway', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the pathway')),
                ('evidence', models.TextField(blank=True, help_text='Evidence or source for this pathway link')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Confidence level of this pathway association', max_length=10)),
                ('species', models.CharField(default='Homo sapiens', help_text='Species for this pathway', max_length=255)),
                ('last_fetched', models.DateTimeField(auto_now=True, help_text='When this data was last updated from Reactome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_interactions', to='compounds.target')),
            ],
            options={
                'verbose_name': 'Target-Pathway Interaction',
                'verbose_name_plural': 'Target-Pathway Interactions',
                'ordering': ['target__name', 'pathway_name'],
                'unique_together': {('target', 'reactome_id')},
            },
        ),
        migrations.CreateModel(
            name='CompoundPathwayEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(blank=True, help_text='Mechanism type (e.g., agonist, inhibitor) that causes this effect', max_length=50)),
                ('effect_type', models.CharField(choices=[('activating', 'Activating'), ('inhibiting', 'Inhibiting'), ('modulating', 'Modulating'), ('unknown', 'Unknown')], help_text='Predicted effect on the pathway', max_length=20)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Confidence level of this predicted effect', max_length=10)),
                ('strength', models.FloatField(default=0.5, help_text='Estimated strength of effect (0.0 to 1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_effects', to='compounds.compound')),
                ('inferred_from', models.ForeignKey(help_text='Target through which this effect is inferred', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounds.target')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_effects', to='compounds.targetpathwayinteraction')),
            ],
            options={
                'verbose_name': 'Compound Pathway Effect',
                'verbose_name_plural': 'Compound Pathway Effects',
                'ordering': ['compound__name', 'pathway__pathway_name'],
                'unique_together': {('compound', 'pathway', 'inferred_from')},
            },
        ),
    ]
