# Generated by Django 5.2.4 on 2025-07-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0026_target_ensembl_id_target_gene_name_target_uniprot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='gene_name',
            field=models.CharField(blank=True, help_text='Gene name/symbol (e.g., HTR2A, DRD2)', max_length=50, null=True),
        ),
    ]
