# Generated by Django 5.2.4 on 2025-07-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0027_fix_gene_name_nullable'),
    ]

    operations = [
        # Remove CompoundPathwayEffect model (has foreign key to TargetPathwayInteraction)
        migrations.DeleteModel(
            name='CompoundPathwayEffect',
        ),
        # Remove TargetPathwayInteraction model
        migrations.DeleteModel(
            name='TargetPathwayInteraction',
        ),
        # Remove pathway-related fields from Target model
        migrations.RemoveField(
            model_name='target',
            name='uniprot_id',
        ),
        migrations.RemoveField(
            model_name='target',
            name='ensembl_id',
        ),
    ]
