# Generated by Django 5.2.4 on 2026-02-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0030_compoundmolpropprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundTargetContextConsensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', models.CharField(db_index=True, max_length=255)),
                ('species', models.CharField(blank=True, max_length=255)),
                ('tissue_or_cell_line', models.CharField(blank=True, max_length=255)),
                ('assay_type', models.CharField(blank=True, max_length=255)),
                ('dose_concentration', models.CharField(blank=True, max_length=255)),
                ('exposure_time', models.CharField(blank=True, max_length=255)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('consensus_mechanism', models.CharField(choices=[('agonist', 'Agonist'), ('antagonist', 'Antagonist'), ('partial_agonist', 'Partial Agonist'), ('inverse_agonist', 'Inverse Agonist'), ('pam', 'Positive Allosteric Modulator'), ('nam', 'Negative Allosteric Modulator'), ('inhibitor', 'Inhibitor'), ('inducer', 'Inducer'), ('activator', 'Activator'), ('binder', 'Binder'), ('substrate', 'Substrate'), ('modulator', 'Modulator'), ('blocker', 'Blocker'), ('opener', 'Opener'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('consensus_confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('has_conflict', models.BooleanField(default=False)),
                ('unresolved_reason', models.CharField(blank=True, max_length=255)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('total_weight', models.FloatField(default=0.0)),
                ('mechanism_weights', models.JSONField(blank=True, default=dict)),
                ('source_breakdown', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_context_consensus', to='compounds.compound')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_context_consensus', to='compounds.target')),
            ],
            options={
                'verbose_name': 'Compound-Target Context Consensus',
                'verbose_name_plural': 'Compound-Target Context Consensus',
                'indexes': [models.Index(fields=['compound', 'target'], name='cti_ctx_compound_target_idx'), models.Index(fields=['consensus_mechanism'], name='cti_ctx_mechanism_idx'), models.Index(fields=['consensus_confidence'], name='cti_ctx_conf_idx'), models.Index(fields=['has_conflict'], name='cti_ctx_conflict_idx')],
                'unique_together': {('compound', 'target', 'context_key')},
            },
        ),
        migrations.CreateModel(
            name='CompoundTargetInteractionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Evidence source (e.g., IUPHAR, BindingDB, DrugBank, DGIdb, PharmGKB)', max_length=50)),
                ('source_record_id', models.CharField(blank=True, help_text='Source-native interaction identifier', max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('evidence_uid', models.CharField(help_text='Deterministic hash used to deduplicate imported evidence rows', max_length=64, unique=True)),
                ('raw_action_type', models.CharField(blank=True, max_length=255)),
                ('raw_mechanism', models.CharField(blank=True, max_length=500)),
                ('canonical_mechanism', models.CharField(choices=[('agonist', 'Agonist'), ('antagonist', 'Antagonist'), ('partial_agonist', 'Partial Agonist'), ('inverse_agonist', 'Inverse Agonist'), ('pam', 'Positive Allosteric Modulator'), ('nam', 'Negative Allosteric Modulator'), ('inhibitor', 'Inhibitor'), ('inducer', 'Inducer'), ('activator', 'Activator'), ('binder', 'Binder'), ('substrate', 'Substrate'), ('modulator', 'Modulator'), ('blocker', 'Blocker'), ('opener', 'Opener'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('species', models.CharField(blank=True, max_length=255)),
                ('tissue_or_cell_line', models.CharField(blank=True, max_length=255)),
                ('assay_type', models.CharField(blank=True, max_length=255)),
                ('dose_concentration', models.CharField(blank=True, max_length=255)),
                ('exposure_time', models.CharField(blank=True, max_length=255)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('evidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('evidence_weight', models.FloatField(default=0.5)),
                ('notes', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('context_key', models.CharField(db_index=True, help_text='Deterministic context key: species+tissue+assay+dose+time+route', max_length=255)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_interaction_evidence', to='compounds.compound')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_interaction_evidence', to='compounds.target')),
            ],
            options={
                'verbose_name': 'Compound-Target Interaction Evidence',
                'verbose_name_plural': 'Compound-Target Interaction Evidence',
                'ordering': ['-imported_at'],
                'indexes': [models.Index(fields=['compound', 'target'], name='cti_ev_compound_target_idx'), models.Index(fields=['source'], name='cti_ev_source_idx'), models.Index(fields=['canonical_mechanism'], name='cti_ev_mechanism_idx'), models.Index(fields=['evidence_level'], name='cti_ev_level_idx')],
            },
        ),
    ]
