# Generated by Django 5.2.4 on 2026-02-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0031_compoundtargetcontextconsensus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundtargetinteractionevidence',
            name='affinity_raw_value',
            field=models.CharField(blank=True, help_text='Original raw affinity value from source record', max_length=64),
        ),
        migrations.AddField(
            model_name='compoundtargetinteractionevidence',
            name='affinity_relation',
            field=models.CharField(blank=True, help_text='Reported relation/operator (e.g., =, <, >, ~)', max_length=10),
        ),
        migrations.AddField(
            model_name='compoundtargetinteractionevidence',
            name='affinity_type',
            field=models.CharField(blank=True, help_text='Reported affinity metric (e.g., Ki, Kd, IC50, EC50)', max_length=20),
        ),
        migrations.AddField(
            model_name='compoundtargetinteractionevidence',
            name='affinity_units',
            field=models.CharField(blank=True, help_text='Original affinity units from source record', max_length=32),
        ),
        migrations.AddField(
            model_name='compoundtargetinteractionevidence',
            name='affinity_value_nm',
            field=models.FloatField(blank=True, help_text='Normalized affinity value in nM for cross-source comparisons', null=True),
        ),
        migrations.AddIndex(
            model_name='compoundtargetinteractionevidence',
            index=models.Index(fields=['affinity_value_nm'], name='cti_ev_affinity_nm_idx'),
        ),
    ]
