# Generated by Django 5.2.4 on 2026-02-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0032_compoundtargetinteractionevidence_affinity_raw_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundtargetinteractionevidence',
            name='source_row_uid',
            field=models.CharField(blank=True, help_text='Stable row fingerprint for fast resume/skip across reruns', max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='compoundtargetinteractionevidence',
            index=models.Index(fields=['source_row_uid'], name='cti_ev_row_uid_idx'),
        ),
    ]
