# Generated by Django 5.2.4 on 2026-02-12 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0033_compoundtargetinteractionevidence_source_row_uid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundKnowledgeGraphRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], default='running', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('request_hash', models.CharField(db_index=True, max_length=64)),
                ('include_internet', models.BooleanField(default=True)),
                ('max_edges', models.PositiveIntegerField(default=25)),
                ('edges_created', models.PositiveIntegerField(default=0)),
                ('edges_rejected', models.PositiveIntegerField(default=0)),
                ('edges_validated', models.PositiveIntegerField(default=0)),
                ('cached_response_used', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('moderation_notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph_runs', to='compounds.compound')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_knowledge_graph_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompoundKnowledgeGraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_kind', models.CharField(choices=[('compound', 'Compound'), ('target', 'Target'), ('mechanism', 'Mechanism'), ('pathway', 'Pathway'), ('gene', 'Gene'), ('effect', 'Effect'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('subject_label', models.CharField(max_length=255)),
                ('predicate', models.CharField(max_length=100)),
                ('object_kind', models.CharField(choices=[('compound', 'Compound'), ('target', 'Target'), ('mechanism', 'Mechanism'), ('pathway', 'Pathway'), ('gene', 'Gene'), ('effect', 'Effect'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('object_label', models.CharField(max_length=255)),
                ('canonical_mechanism', models.CharField(choices=[('agonist', 'Agonist'), ('antagonist', 'Antagonist'), ('partial_agonist', 'Partial Agonist'), ('inverse_agonist', 'Inverse Agonist'), ('pam', 'Positive Allosteric Modulator'), ('nam', 'Negative Allosteric Modulator'), ('inhibitor', 'Inhibitor'), ('inducer', 'Inducer'), ('activator', 'Activator'), ('binder', 'Binder'), ('substrate', 'Substrate'), ('modulator', 'Modulator'), ('blocker', 'Blocker'), ('opener', 'Opener'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('evidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('source_title', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('evidence_snippet', models.TextField(blank=True)),
                ('db_validation_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('conflicting', 'Conflicting'), ('novel', 'Novel'), ('unresolved', 'Unresolved'), ('rejected', 'Rejected')], default='unresolved', max_length=20)),
                ('moderation_status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('moderation_reason', models.CharField(blank=True, max_length=255)),
                ('edge_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound', models.ForeignKey(help_text='Anchor compound for this graph edge', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph_edges', to='compounds.compound')),
                ('related_compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_knowledge_graph_edges', to='compounds.compound')),
                ('related_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_graph_edges', to='compounds.target')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='compounds.compoundknowledgegraphrun')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='compoundknowledgegraphrun',
            index=models.Index(fields=['compound', 'created_at'], name='ckgr_comp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='compoundknowledgegraphrun',
            index=models.Index(fields=['compound', 'status'], name='ckgr_comp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='compoundknowledgegraphrun',
            index=models.Index(fields=['request_hash'], name='ckgr_req_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='compoundknowledgegraphedge',
            index=models.Index(fields=['compound', 'created_at'], name='ckge_comp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='compoundknowledgegraphedge',
            index=models.Index(fields=['db_validation_status'], name='ckge_validation_idx'),
        ),
        migrations.AddIndex(
            model_name='compoundknowledgegraphedge',
            index=models.Index(fields=['canonical_mechanism'], name='ckge_mechanism_idx'),
        ),
        migrations.AddIndex(
            model_name='compoundknowledgegraphedge',
            index=models.Index(fields=['predicate'], name='ckge_predicate_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compoundknowledgegraphedge',
            unique_together={('run', 'edge_hash')},
        ),
    ]
