# Generated by Django 5.2.4 on 2026-02-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0034_compoundknowledgegraphrun_compoundknowledgegraphedge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundknowledgegraphrun',
            name='parsed_output',
            field=models.JSONField(blank=True, default=dict, help_text='Normalized Gemini JSON payload captured before moderation filtering'),
        ),
    ]
