# Generated by Django 5.2.4 on 2026-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0035_compoundknowledgegraphrun_parsed_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='anabolic_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Relative anabolic rating (commonly testosterone=100 baseline).', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='androgenic_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Relative androgenic rating (commonly testosterone=100 baseline).', max_digits=7, null=True),
        ),
    ]
