# Generated by Django 5.2.4 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0037_compound_steroid_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='enriched_at',
            field=models.DateTimeField(blank=True, help_text='Last time external enrichment sources were checked', null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='mechanism_of_action_summary',
            field=models.TextField(blank=True, default='', help_text='Primary external mechanism summary from upstream sources'),
        ),
        migrations.AddField(
            model_name='compound',
            name='molecular_formula',
            field=models.CharField(blank=True, default='', help_text='Molecular formula (for example C8H10N4O2)', max_length=100),
        ),
        migrations.AddField(
            model_name='compound',
            name='molecular_weight',
            field=models.CharField(blank=True, default='', help_text='Molecular weight in g/mol', max_length=50),
        ),
        migrations.AddField(
            model_name='compound',
            name='pubchem_cid',
            field=models.CharField(blank=True, default='', help_text='PubChem Compound ID (CID)', max_length=32),
        ),
        migrations.AddField(
            model_name='compound',
            name='pubmed_interactions',
            field=models.JSONField(blank=True, default=list, help_text='Cached PubMed interaction-focused references'),
        ),
    ]
