# Generated by Django 5.2.4 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0038_compound_external_enrichment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='inchi',
            field=models.CharField(blank=True, default='', help_text='IUPAC International Chemical Identifier (InChI)', max_length=4000),
        ),
        migrations.AddField(
            model_name='compound',
            name='inchi_key',
            field=models.CharField(blank=True, default='', help_text='Hashed InChIKey identifier', max_length=64),
        ),
        migrations.AddField(
            model_name='compound',
            name='iupac_name',
            field=models.CharField(blank=True, default='', help_text='IUPAC preferred compound name', max_length=1000),
        ),
    ]
