# Generated by Django 5.2.4 on 2026-02-26 09:24

from django.db import migrations, models


TMP_NULL_PREFIX = 'MIGCIDNULL_'


def normalize_pubchem_cid_values(apps, schema_editor):
    Compound = apps.get_model('compounds', 'Compound')

    # Normalize whitespace and convert empty strings to unique placeholders.
    for row in Compound.objects.exclude(pubchem_cid__isnull=True).values('id', 'pubchem_cid'):
        raw_value = (row.get('pubchem_cid') or '')
        cleaned_value = raw_value.strip()
        if not cleaned_value:
            Compound.objects.filter(id=row['id']).update(pubchem_cid=f"{TMP_NULL_PREFIX}{row['id']}")
            continue
        if cleaned_value != raw_value:
            Compound.objects.filter(id=row['id']).update(pubchem_cid=cleaned_value)

    # Keep the first occurrence of duplicate CIDs and replace the rest with unique placeholders.
    seen_cids = set()
    for row in Compound.objects.exclude(pubchem_cid__isnull=True).order_by('id').values('id', 'pubchem_cid'):
        cid = row.get('pubchem_cid')
        if cid in seen_cids:
            Compound.objects.filter(id=row['id']).update(pubchem_cid=f"{TMP_NULL_PREFIX}{row['id']}")
            continue
        seen_cids.add(cid)

def finalize_pubchem_cid_values(apps, schema_editor):
    Compound = apps.get_model('compounds', 'Compound')
    Compound.objects.filter(pubchem_cid__startswith=TMP_NULL_PREFIX).update(pubchem_cid=None)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0039_compound_inchi_compound_inchi_key_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_pubchem_cid_values, noop_reverse),
        migrations.AlterField(
            model_name='compound',
            name='pubchem_cid',
            field=models.CharField(blank=True, help_text='PubChem Compound ID (CID)', max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(finalize_pubchem_cid_values, noop_reverse),
    ]
