# Generated by Django 5.2.4 on 2026-02-26 09:31

from django.db import migrations, models


TMP_NULL_PREFIX = 'MIGINCHINULL_'


def normalize_inchi_values(apps, schema_editor):
    Compound = apps.get_model('compounds', 'Compound')

    # Normalize whitespace and convert empty strings to unique placeholders.
    for row in Compound.objects.exclude(inchi__isnull=True).values('id', 'inchi'):
        raw_value = (row.get('inchi') or '')
        cleaned_value = raw_value.strip()
        if not cleaned_value:
            Compound.objects.filter(id=row['id']).update(inchi=f"{TMP_NULL_PREFIX}{row['id']}")
            continue
        if cleaned_value != raw_value:
            Compound.objects.filter(id=row['id']).update(inchi=cleaned_value)

    # Keep first occurrence of duplicate InChI values and clear the rest later.
    seen_inchi = set()
    for row in Compound.objects.exclude(inchi__isnull=True).order_by('id').values('id', 'inchi'):
        inchi_value = row.get('inchi')
        if inchi_value in seen_inchi:
            Compound.objects.filter(id=row['id']).update(inchi=f"{TMP_NULL_PREFIX}{row['id']}")
            continue
        seen_inchi.add(inchi_value)


def finalize_inchi_values(apps, schema_editor):
    Compound = apps.get_model('compounds', 'Compound')
    Compound.objects.filter(inchi__startswith=TMP_NULL_PREFIX).update(inchi=None)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0040_alter_compound_pubchem_cid'),
    ]

    operations = [
        migrations.RunPython(normalize_inchi_values, noop_reverse),
        migrations.AlterField(
            model_name='compound',
            name='inchi',
            field=models.CharField(blank=True, help_text='IUPAC International Chemical Identifier (InChI)', max_length=4000, null=True, unique=True),
        ),
        migrations.RunPython(finalize_inchi_values, noop_reverse),
    ]
