# Generated by Django 5.2.4 on 2026-02-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0041_alter_compound_inchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='bindingdb_id',
            field=models.CharField(blank=True, help_text='BindingDB monomer ID (e.g., 50058958)', max_length=32, null=True, unique=True),
        ),
    ]
