# Generated by Django 5.2.4 on 2026-03-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0042_compound_bindingdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundsteroidrating',
            name='ester_ratio',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Fraction of active (ester-free) hormone per mg of compound. Computed as free_MW / compound_MW.  Oral / ester-free = 1.0.', max_digits=5),
        ),
    ]
