# Generated by Django 5.2.4 on 2026-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0044_compound_standard_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundsafetyscreening',
            name='bladder_toxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='0 = Protective effect; 1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
        migrations.AlterField(
            model_name='compoundsafetyscreening',
            name='cardiovascular_risk',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='0 = Protective effect; 1 = No risk observed; 5 = Lethal risk', null=True),
        ),
        migrations.AlterField(
            model_name='compoundsafetyscreening',
            name='hpta_suppression',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='0 = Protective effect; 1 = No suppression observed; 5 = Full suppression', null=True),
        ),
        migrations.AlterField(
            model_name='compoundsafetyscreening',
            name='kidney_toxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='0 = Protective effect; 1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
        migrations.AlterField(
            model_name='compoundsafetyscreening',
            name='liver_toxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='0 = Protective effect; 1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
        migrations.AlterField(
            model_name='compoundsafetyscreening',
            name='lung_toxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='0 = Protective effect; 1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
        migrations.AlterField(
            model_name='compoundsafetyscreening',
            name='neurotoxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='0 = Protective effect; 1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
        migrations.AlterField(
            model_name='compoundsafetyscreening',
            name='pancreas_toxicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='0 = Protective effect; 1 = No toxicity observed; 5 = Lethal toxicity', null=True),
        ),
    ]
