# Generated by Django 5.2.4 on 2026-08-25 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0045_alter_compoundsafetyscreening_bladder_toxicity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetabolicImportReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('source_version', models.CharField(max_length=64)),
                ('source_record_id', models.CharField(max_length=255)),
                ('raw_name', models.CharField(max_length=255)),
                ('raw_identifiers', models.JSONField(blank=True, default=dict)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'source_record_id', 'source_version'), name='unique_metabolic_review_record')],
            },
        ),
        migrations.CreateModel(
            name='MetabolicInteractionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enzyme', models.CharField(db_index=True, max_length=32)),
                ('role', models.CharField(choices=[('substrate', 'Substrate'), ('inhibitor', 'Reversible inhibitor'), ('inducer', 'Inducer'), ('time_dependent_inhibitor', 'Time-dependent inhibitor')], max_length=32)),
                ('strength', models.CharField(choices=[('unknown', 'Unknown'), ('weak', 'Weak'), ('moderate', 'Moderate'), ('strong', 'Strong'), ('sensitive', 'Sensitive substrate')], default='unknown', max_length=16)),
                ('evidence_tier', models.CharField(choices=[('label_clinical', 'FDA/label clinical'), ('curated_human', 'Curated human'), ('experimental', 'Experimental'), ('consensus', 'Consensus'), ('predicted', 'Predicted')], max_length=24)),
                ('narrow_therapeutic_index', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=32)),
                ('source_record_id', models.CharField(max_length=255)),
                ('source_version', models.CharField(max_length=64)),
                ('source_url', models.URLField(blank=True)),
                ('source_checksum', models.CharField(max_length=64)),
                ('quoted_classification', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, max_length=32)),
                ('ki_nm', models.FloatField(blank=True, null=True)),
                ('ic50_nm', models.FloatField(blank=True, null=True)),
                ('fraction_metabolized', models.FloatField(blank=True, null=True)),
                ('half_life_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField()),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metabolic_evidence', to='compounds.compound')),
            ],
            options={
                'indexes': [models.Index(fields=['compound', 'enzyme', 'role'], name='metabolic_compound_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_record_id', 'source_version'), name='unique_metabolic_source_record')],
            },
        ),
    ]
