# Generated by Django 5.2.4 on 2026-08-26 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0046_metabolicimportreview_metabolicinteractionevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetabolicSourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('source_version', models.CharField(max_length=64)),
                ('source_url', models.URLField()),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('encrypted_payload', models.BinaryField()),
                ('encryption_key_version', models.CharField(max_length=32)),
                ('manifest', models.JSONField(default=dict)),
                ('retrieved_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetabolicValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_version', models.CharField(max_length=32)),
                ('model_version', models.CharField(max_length=64)),
                ('case_count', models.PositiveIntegerField()),
                ('high_risk_sensitivity', models.FloatField()),
                ('specificity', models.FloatField()),
                ('coverage', models.FloatField()),
                ('prediction_promotions', models.PositiveIntegerField()),
                ('confusion_matrix', models.JSONField(default=dict)),
                ('passed_metrics', models.BooleanField(default=False)),
                ('pharmacist_signed_off', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='metabolicimportreview',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='metabolicimportreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MetabolicReferenceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_version', models.CharField(db_index=True, max_length=32)),
                ('expected_tier', models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('hypothesis', 'Hypothesis'), ('unknown', 'Unknown')], max_length=16)),
                ('expected_mechanism', models.CharField(blank=True, max_length=64)),
                ('rationale', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=255)),
                ('pharmacist_approved_at', models.DateTimeField(blank=True, null=True)),
                ('perpetrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compounds.compound')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compounds.compound')),
            ],
        ),
        migrations.CreateModel(
            name='MetabolicSourceDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('added', models.JSONField(default=list)),
                ('changed', models.JSONField(default=list)),
                ('removed', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compounds.metabolicsourcesnapshot')),
                ('previous_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compounds.metabolicsourcesnapshot')),
            ],
        ),
    ]
