# Generated by Django 5.2.4 on 2026-08-25 23:54

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.clinical_document_path)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('content_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('review', 'Needs review'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_version', models.CharField(max_length=32)),
                ('consented_at', models.DateTimeField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex_at_birth', models.CharField(blank=True, max_length=16)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pregnancy_status', models.CharField(blank=True, max_length=24)),
                ('smoking_status', models.CharField(blank=True, max_length=24)),
                ('egfr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('egfr_measured_at', models.DateField(blank=True, null=True)),
                ('child_pugh_class', models.CharField(blank=True, max_length=1)),
                ('child_pugh_assessed_at', models.DateField(blank=True, null=True)),
                ('diagnoses', models.JSONField(blank=True, default=list)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalProfileDraftValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('value', models.JSONField()),
                ('provenance', models.JSONField(default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_values', to='accounts.clinicaldocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'field_name'), name='unique_document_draft_field')],
            },
        ),
        migrations.CreateModel(
            name='PharmacogenomicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=32)),
                ('diplotype', models.CharField(blank=True, max_length=64)),
                ('phenotype', models.CharField(blank=True, max_length=64)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacogenomic_results', to='accounts.clinicalprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'gene'), name='unique_profile_pgx_gene')],
            },
        ),
    ]
