# Generated by Django 5.2.4 on 2026-08-26 00:48

import accounts.models
import accounts.private_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clinicaldocument_clinicalprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldocument',
            name='encryption_key_version',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='extraction_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='purge_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='scan_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicaldocument',
            name='file',
            field=models.FileField(storage=accounts.private_storage.EncryptedPrivateStorage(), upload_to=accounts.models.clinical_document_path),
        ),
        migrations.AlterField(
            model_name='clinicaldocument',
            name='status',
            field=models.CharField(choices=[('quarantined', 'Quarantined'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('infected', 'Infected'), ('extraction_pending', 'Extraction pending'), ('review', 'Needs review'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('purged', 'Purged')], default='quarantined', max_length=24),
        ),
        migrations.CreateModel(
            name='ClinicalAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=48)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.clinicaldocument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
