# Generated by Django 5.2.4 on 2025-07-28 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0028_remove_pathway_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Longevity-enhancing)', max_length=64, unique=True)),
                ('description', models.TextField(help_text='Description of this scoring category')),
                ('slug', models.SlugField(help_text='URL-safe slug for this category', unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji for display', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is actively scored')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scoring Category',
                'verbose_name_plural': 'Scoring Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=64)),
                ('training_started', models.DateTimeField()),
                ('training_completed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Training Running'), ('completed', 'Training Completed'), ('failed', 'Training Failed')], default='running', max_length=20)),
                ('training_samples', models.IntegerField(default=0)),
                ('validation_accuracy', models.FloatField(blank=True, null=True)),
                ('validation_loss', models.FloatField(blank=True, null=True)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compound_ranker.scoringcategory')),
            ],
            options={
                'verbose_name': 'Model Training Log',
                'verbose_name_plural': 'Model Training Logs',
                'ordering': ['-training_started'],
            },
        ),
        migrations.CreateModel(
            name='CompoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Predicted score (0-1 range)')),
                ('confidence', models.FloatField(help_text='Model confidence in prediction (0-1 range)')),
                ('model_version', models.CharField(blank=True, help_text='Version of ML model used', max_length=64)),
                ('features_used', models.JSONField(default=dict, help_text='Features used for this prediction')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_scores', to='compounds.compound')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compound_ranker.scoringcategory')),
            ],
            options={
                'verbose_name': 'Compound Score',
                'verbose_name_plural': 'Compound Scores',
                'ordering': ['-score', '-timestamp'],
                'indexes': [models.Index(fields=['category', '-score'], name='compound_ra_categor_e149e9_idx'), models.Index(fields=['compound', 'category'], name='compound_ra_compoun_53950f_idx'), models.Index(fields=['timestamp'], name='compound_ra_timesta_135314_idx')],
                'unique_together': {('compound', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserCompoundAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.FloatField(help_text='User-provided score (0-1 range)')),
                ('notes', models.TextField(blank=True, help_text='User notes about this scoring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this annotation has been verified')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compound_ranker.scoringcategory')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.compound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Compound Annotation',
                'verbose_name_plural': 'User Compound Annotations',
                'ordering': ['-created_at'],
                'unique_together': {('compound', 'category', 'user')},
            },
        ),
    ]
