# Generated by Django 5.2.4 on 2025-07-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_requests', '0002_compoundversion'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS change_requests_appliedchange;",
            reverse_sql="-- Cannot reverse this migration"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS change_requests_changerequestcomment;",
            reverse_sql="-- Cannot reverse this migration"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS change_requests_changerequest;",
            reverse_sql="-- Cannot reverse this migration"
        ),
    ]
