# Generated by Django 5.2.4 on 2025-07-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_requests', '0002_compoundversion'),
    ]

    operations = [
    ]
