# Generated by Django 5.2.4 on 2025-07-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_requests', '0003_remove_change_request_tables'),
    ]

    operations = [
    ]
