from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from compounds.models import Compound


class ResearchSnippet(models.Model):
    """
    Research snippet system - user-contributed research content for compounds.
    """
    
    VISIBILITY_CHOICES = [
        ('draft', 'Draft'),
        ('public', 'Public'),
    ]
    
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('submitted', 'Submitted'),
        ('needs_review', 'Needs Reviews'),
        ('verified', 'Verified'),
        ('flagged', 'Flagged'),
        ('rejected', 'Rejected'),
    ]
    
    SNIPPET_TYPE_CHOICES = [
        ('general', 'General Research'),
        ('mechanism', 'Mechanism of Action'),
        ('pharmacology', 'Pharmacology'),
        ('safety', 'Safety Data'),
        ('clinical', 'Clinical Studies'),
        ('dosage', 'Dosage Information'),
        ('interaction', 'Drug Interactions'),
        ('experience', 'User Experience'),
        ('other', 'Other'),
    ]
    
    # Core fields
    title = models.CharField(max_length=300, help_text="Brief title describing the research snippet")
    content = models.TextField(help_text="The main research content or findings")
    compound = models.ForeignKey(
        Compound, 
        on_delete=models.CASCADE, 
        related_name='research_snippets',
        help_text="Which compound this research relates to"
    )
    snippet_type = models.CharField(
        max_length=50, 
        choices=SNIPPET_TYPE_CHOICES, 
        default='general',
        help_text="Category of research"
    )
    
    # Visibility and status
    visibility = models.CharField(
        max_length=20, 
        choices=VISIBILITY_CHOICES, 
        default='public',
        help_text="Snippet visibility - all snippets are public unless saved as draft"
    )
    status = models.CharField(
        max_length=20, 
        choices=STATUS_CHOICES, 
        default='draft',
        help_text="Review status of the snippet"
    )
    
    # Source and credibility
    source_title = models.CharField(
        max_length=500, 
        blank=True,
        help_text="Title of the research paper, study, or source"
    )
    source_url = models.URLField(
        blank=True,
        help_text="Link to the original source (PubMed, journal, etc.)"
    )
    doi = models.CharField(
        max_length=100, 
        blank=True,
        help_text="Digital Object Identifier (DOI) if available"
    )
    # User tracking
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name='submitted_snippets'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # AI and review fields
    ai_summary = models.TextField(
        blank=True,
        help_text="AI-generated summary of the content"
    )
    ai_generated = models.BooleanField(
        default=False,
        help_text="Whether this snippet was generated by AI"
    )
    
    # Analytics
    view_count = models.PositiveIntegerField(default=0)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = "Research Snippet"
        verbose_name_plural = "Research Snippets"
    
    def __str__(self):
        return f"{self.title} - {self.compound.name}"
    
    @property
    def net_score(self):
        """Calculate net voting score (positive - negative votes)"""
        return self.reviews.aggregate(
            positive=models.Count('id', filter=models.Q(vote_type='validate')),
            negative=models.Count('id', filter=models.Q(vote_type='reject'))
        )
    
    @property
    def confidence_level(self):
        """Calculate confidence level based on community votes"""
        scores = self.net_score
        positive = scores.get('positive', 0)
        negative = scores.get('negative', 0)
        total_votes = positive + negative
        
        if total_votes == 0:
            return 'Unknown'
        
        # Calculate approval ratio
        approval_ratio = positive / total_votes if total_votes > 0 else 0
        
        # Determine confidence based on votes and approval ratio
        if total_votes >= 5 and approval_ratio >= 0.8:
            return 'High'
        elif total_votes >= 3 and approval_ratio >= 0.6:
            return 'Medium'
        elif total_votes >= 1:
            return 'Low/No'
        else:
            return 'Unknown'
    
    @property
    def confidence_color(self):
        """Return Bootstrap color class for confidence level"""
        confidence_colors = {
            'High': 'success',
            'Medium': 'warning',
            'Low/No': 'danger',
            'Unknown': 'secondary'
        }
        return confidence_colors.get(self.confidence_level, 'secondary')
    
    @property
    def verification_threshold(self):
        """Dynamic verification threshold based on views and complexity"""
        if self.view_count < 100:
            return 3  # Lower threshold for new snippets
        elif self.view_count < 500:
            return 5  # Medium threshold
        else:
            return 8  # Higher threshold for popular content
    
    def update_status(self):
        """Auto-update status based on review votes"""
        scores = self.net_score
        positive = scores.get('positive', 0)
        negative = scores.get('negative', 0)
        net = positive - negative
        threshold = self.verification_threshold
        
        if negative >= 3:
            self.status = 'flagged'
        elif net >= threshold and positive >= threshold:
            self.status = 'verified'
        elif self.reviews.count() > 0:
            self.status = 'needs_review'
        else:
            self.status = 'submitted'
        
        self.save()


class SnippetReview(models.Model):
    """
    Community voting/review system for research snippets.
    """
    
    VOTE_CHOICES = [
        ('validate', 'Validate ✔️'),
        ('reject', 'Reject ❌'),
    ]
    
    snippet = models.ForeignKey(
        ResearchSnippet, 
        on_delete=models.CASCADE, 
        related_name='reviews'
    )
    reviewer = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name='snippet_reviews'
    )
    vote_type = models.CharField(max_length=20, choices=VOTE_CHOICES)
    comment = models.TextField(
        blank=True,
        help_text="Optional feedback on the snippet quality"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('snippet', 'reviewer')
        ordering = ['-created_at']
        verbose_name = "Snippet Review"
        verbose_name_plural = "Snippet Reviews"
    
    def __str__(self):
        return f"{self.reviewer} {self.vote_type} {self.snippet.title}"


class SnippetTag(models.Model):
    """
    Tagging system for categorizing snippets by domain/topic.
    """
    
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    color = models.CharField(
        max_length=7, 
        default='#007bff',
        help_text="Hex color code for tag display"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['name']
        verbose_name = "Snippet Tag"
        verbose_name_plural = "Snippet Tags"
    
    def __str__(self):
        return self.name


class SnippetTagging(models.Model):
    """
    Many-to-many through table for snippet-tag relationships.
    """
    
    snippet = models.ForeignKey(ResearchSnippet, on_delete=models.CASCADE)
    tag = models.ForeignKey(SnippetTag, on_delete=models.CASCADE)
    tagged_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
        null=True, 
        blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('snippet', 'tag')
        verbose_name = "Snippet Tagging"
        verbose_name_plural = "Snippet Taggings"


# Add the many-to-many relationship to ResearchSnippet
ResearchSnippet.add_to_class(
    'tags',
    models.ManyToManyField(
        SnippetTag,
        through=SnippetTagging,
        related_name='snippets',
        blank=True
    )
)


class UserRole(models.Model):
    """
    Extended roles for community moderation.
    """
    
    ROLE_CHOICES = [
        ('guest', 'Guest'),
        ('authenticated', 'Authenticated User'),
        ('trusted_reviewer', 'Trusted Reviewer'),
        ('moderator', 'Moderator'),
        ('admin', 'Administrator'),
    ]
    
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name='research_role'
    )
    role = models.CharField(
        max_length=20, 
        choices=ROLE_CHOICES, 
        default='authenticated'
    )
    vote_weight = models.FloatField(
        default=1.0,
        help_text="Weight multiplier for this user's votes"
    )
    can_moderate = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "User Role"
        verbose_name_plural = "User Roles"
    
    def __str__(self):
        return f"{self.user.username} - {self.role}"


class ResearchSettings(models.Model):
    """
    Global settings for the research snippet system.
    """
    
    # Feature toggles
    public_submissions_enabled = models.BooleanField(
        default=True,
        help_text="Allow users to submit public research snippets"
    )
    require_review_flair = models.BooleanField(
        default=True,
        help_text="Show 'Needs Reviews' badges on unverified snippets"
    )
    higher_confirmation_rate = models.BooleanField(
        default=False,
        help_text="Require more votes for popular/trending snippets"
    )
    ai_summaries_enabled = models.BooleanField(
        default=True,
        help_text="Enable AI-powered summarization features"
    )
    
    # Thresholds
    min_votes_for_flair = models.IntegerField(
        default=1,
        help_text="Minimum votes before showing review flair"
    )
    verification_threshold = models.IntegerField(
        default=3,
        help_text="Minimum positive votes for verification"
    )
    flagging_threshold = models.IntegerField(
        default=2,
        help_text="Minimum rejection votes for flagging"
    )
    high_confidence_threshold = models.IntegerField(
        default=5,
        help_text="Votes needed for high-confidence validation"
    )
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "Research Settings"
        verbose_name_plural = "Research Settings"
    
    def __str__(self):
        return f"Research Settings (Updated: {self.updated_at.strftime('%Y-%m-%d')})"


class SnippetComment(models.Model):
    """
    Standalone comment system for research snippets.
    Independent of the review/voting system.
    """
    
    snippet = models.ForeignKey(
        ResearchSnippet, 
        on_delete=models.CASCADE, 
        related_name='comments'
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name='snippet_comments'
    )
    content = models.TextField(help_text="Your comment about this research")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = "Snippet Comment"
        verbose_name_plural = "Snippet Comments"
    
    def __str__(self):
        return f"{self.author.username} on {self.snippet.title}"
