# Generated by Django 5.2.4 on 2025-07-20 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0010_compoundtargetinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mcg', 'mcg'), ('ml', 'ml'), ('drops', 'drops'), ('units', 'units'), ('other', 'Other')], default='mg', max_length=16)),
                ('taken_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.compound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
