# Generated by Django 5.2.4 on 2025-07-23 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0020_alter_compoundmechanismofaction_target_interaction_and_more'),
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundIntakeLog',
            fields=[
            ],
            options={
                'verbose_name': 'Compound Intake Log',
                'verbose_name_plural': 'Compound Intake Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logs.intakelog',),
        ),
        migrations.AlterModelOptions(
            name='intakelog',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AddField(
            model_name='intakelog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intakelog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('compound_added', 'Compound Added'), ('compound_edited', 'Compound Edited'), ('compound_rated', 'Compound Rated'), ('compound_commented', 'Compound Commented'), ('research_added', 'Research Added'), ('research_edited', 'Research Edited'), ('research_commented', 'Research Commented'), ('intake_logged', 'Intake Logged'), ('profile_updated', 'Profile Updated'), ('login', 'Login'), ('logout', 'Logout')], max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.compound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logs.useractivitylog',),
        ),
    ]
