# Generated by Django 5.2.4 on 2025-07-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_compoundintakelog_alter_intakelog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='CompoundIntakeLog',
        ),
        migrations.AlterModelOptions(
            name='intakelog',
            options={},
        ),
        migrations.RemoveField(
            model_name='intakelog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='intakelog',
            name='updated',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
    ]
