# Generated by Codex on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_useractivitylog_compound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakelog',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('', '—'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], default='', max_length=10),
        ),
    ]

