# Generated by Django 5.2.4 on 2026-02-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_intakelog_time_of_day_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakelog',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night'), ('pre-event', 'Pre-event')], default=None, max_length=10, null=True),
        ),
    ]
