# Generated by Django 5.2.4 on 2026-02-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_intakelog_time_of_day'),
        ('logs', '0006_intakelog_time_of_day_pre_event'),
    ]

    operations = [
    ]
