# Generated by Codex on 2026-02-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0008_merge_20260204_2132'),
        ('logs', '0007_merge_20260204_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakelog',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakelog',
            name='stack_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stacks.stackitem'),
        ),
    ]

