# Generated by Django 5.2.4 on 2026-02-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_usergoal_usergoalcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestIPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('total_requests', models.PositiveBigIntegerField(default=0)),
                ('get_requests', models.PositiveBigIntegerField(default=0)),
                ('post_requests', models.PositiveBigIntegerField(default=0)),
                ('other_requests', models.PositiveBigIntegerField(default=0)),
                ('error_requests', models.PositiveBigIntegerField(default=0)),
                ('distinct_paths', models.PositiveIntegerField(default=0)),
                ('last_path', models.CharField(blank=True, max_length=512)),
                ('last_user_agent', models.TextField(blank=True)),
                ('last_user', models.CharField(blank=True, max_length=150)),
                ('abuse_checked_at', models.DateTimeField(blank=True, null=True)),
                ('abuse_confidence_score', models.PositiveIntegerField(blank=True, null=True)),
                ('abuse_total_reports', models.PositiveIntegerField(blank=True, null=True)),
                ('abuse_num_distinct_users', models.PositiveIntegerField(blank=True, null=True)),
                ('abuse_last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('abuse_usage_type', models.CharField(blank=True, max_length=255)),
                ('abuse_isp', models.CharField(blank=True, max_length=255)),
                ('abuse_domain', models.CharField(blank=True, max_length=255)),
                ('abuse_country_code', models.CharField(blank=True, max_length=8)),
                ('abuse_country_name', models.CharField(blank=True, max_length=128)),
                ('abuse_hostnames', models.JSONField(blank=True, default=list)),
                ('abuse_is_public', models.BooleanField(blank=True, null=True)),
                ('abuse_is_whitelisted', models.BooleanField(blank=True, null=True)),
                ('abuse_check_error', models.TextField(blank=True)),
                ('is_throttle_active', models.BooleanField(default=False)),
                ('throttle_limit_per_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at', 'ip_address'],
            },
        ),
        migrations.CreateModel(
            name='RequestIPPathStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=10)),
                ('request_count', models.PositiveBigIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField()),
                ('ip_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_stats', to='logs.requestipprofile')),
            ],
            options={
                'ordering': ['-request_count', 'path'],
                'constraints': [models.UniqueConstraint(fields=('ip_profile', 'path', 'method'), name='unique_ip_path_method_stat')],
            },
        ),
    ]
