# Generated by Django 5.2.4 on 2026-03-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logs", "0010_requestipprofile_requestippathstat"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodworkEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("collected_at", models.DateTimeField()),
                ("panel_name", models.CharField(max_length=160)),
                ("lab_name", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloodwork_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodworkMeasurement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("marker_name", models.CharField(max_length=160)),
                ("value", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(blank=True, max_length=60)),
                ("reference_low", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("reference_high", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="logs.bloodworkentry",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BloodworkRelatedIntake",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_intakes",
                        to="logs.bloodworkentry",
                    ),
                ),
                (
                    "intake_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloodwork_links",
                        to="logs.intakelog",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entry", "intake_log"),
                        name="unique_bloodwork_entry_intake_log",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="bloodworkentry",
            name="related_intake_logs",
            field=models.ManyToManyField(
                blank=True,
                related_name="bloodwork_entries",
                through="logs.BloodworkRelatedIntake",
                to="logs.intakelog",
            ),
        ),
    ]
