# Generated by Django 5.2.4 on 2025-08-07 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0028_remove_pathway_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.compound')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stacks.stack')),
            ],
            options={
                'ordering': ['order', 'added'],
            },
        ),
    ]
