# Generated by Django 5.2.4 on 2025-08-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackitem',
            name='dosage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='intake_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
