# Generated by Django 5.2.4 on 2025-08-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0002_stackitem_dosage_amount_stackitem_intake_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackitem',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='recurrence_unit',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
    ]
