# Generated by Codex on 2026-02-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0003_stackitem_recurrence_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stack',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='stack',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stack',
            name='copied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stack',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='stacks.stack'),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='dosage_unit',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mcg', 'mcg'), ('ml', 'ml'), ('drops', 'drops'), ('units', 'units'), ('other', 'Other')], default='mg', max_length=16),
        ),
    ]

