# Generated by Codex on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0004_stack_visibility_active_copy_and_stackitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackitem',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('', '—'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], default='', max_length=10),
        ),
    ]

