# Generated by Codex on 2026-02-03

from django.db import migrations, models


def blank_to_null(apps, schema_editor):
    StackItem = apps.get_model('stacks', 'StackItem')
    StackItem.objects.filter(time_of_day='').update(time_of_day=None)


def null_to_blank(apps, schema_editor):
    StackItem = apps.get_model('stacks', 'StackItem')
    StackItem.objects.filter(time_of_day__isnull=True).update(time_of_day='')


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0005_stackitem_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackitem',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], default=None, max_length=10, null=True),
        ),
        migrations.RunPython(blank_to_null, reverse_code=null_to_blank),
    ]

