# Generated by Codex on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0006_stackitem_time_of_day_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackitem',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night'), ('pre-event', 'Pre-event')], default=None, max_length=10, null=True),
        ),
    ]

