# Generated by Django 5.2.4 on 2026-02-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0007_alter_stackitem_time_of_day'),
        ('stacks', '0007_stackitem_time_of_day_pre_event'),
    ]

    operations = [
    ]
