# Generated by Codex on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0008_merge_20260204_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

