# Generated by Django 5.2.4 on 2026-02-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0031_compoundtargetcontextconsensus_and_more'),
        ('stacks', '0010_stackriskassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('trait_type', models.CharField(choices=[('benefit', 'Benefit'), ('risk', 'Risk')], default='benefit', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_hypothesis', models.BooleanField(default=False, help_text='Marks hypothesis-only traits (for example oncoprotection hypotheses).')),
                ('min_score', models.FloatField(default=-5.0)),
                ('max_score', models.FloatField(default=5.0)),
                ('default_weight', models.FloatField(default=1.0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='StackDangerousPairRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=16)),
                ('reason', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dangerous_pairs_as_a', to='compounds.compound')),
                ('compound_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dangerous_pairs_as_b', to='compounds.compound')),
            ],
            options={
                'indexes': [models.Index(fields=['compound_a', 'compound_b'], name='st_danger_pair_idx'), models.Index(fields=['is_active'], name='st_danger_active_idx')],
                'unique_together': {('compound_a', 'compound_b')},
            },
        ),
        migrations.CreateModel(
            name='MechanismTraitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(choices=[('agonist', 'Agonist'), ('antagonist', 'Antagonist'), ('partial_agonist', 'Partial Agonist'), ('inverse_agonist', 'Inverse Agonist'), ('pam', 'Positive Allosteric Modulator'), ('nam', 'Negative Allosteric Modulator'), ('inhibitor', 'Inhibitor'), ('inducer', 'Inducer'), ('activator', 'Activator'), ('binder', 'Binder'), ('substrate', 'Substrate'), ('modulator', 'Modulator'), ('blocker', 'Blocker'), ('opener', 'Opener'), ('unknown', 'Unknown')], db_index=True, max_length=50)),
                ('delta', models.FloatField(help_text='Directional trait delta for this mechanism/rule. Typical range: -5..+5')),
                ('base_confidence', models.FloatField(default=0.7, help_text='Rule confidence multiplier in range 0..1.')),
                ('target_name_contains', models.CharField(blank=True, help_text='Optional substring filter to scope this rule to specific target families.', max_length=255)),
                ('species', models.CharField(blank=True, max_length=255)),
                ('assay_type', models.CharField(blank=True, max_length=255)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers are evaluated first and treated as more specific rules.')),
                ('is_active', models.BooleanField(default=True)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanism_rules', to='stacks.stacktrait')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['mechanism', 'is_active'], name='st_rule_mech_active_idx'), models.Index(fields=['trait', 'is_active'], name='st_rule_trait_active_idx')],
            },
        ),
    ]
