# Generated by Django 5.2.4 on 2026-03-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0011_stacktrait_stackdangerouspairrule_mechanismtraitrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackitem',
            name='cycle_off_days',
            field=models.PositiveIntegerField(blank=True, help_text='Rest days per cycle (e.g. 2 for 5-on/2-off).', null=True),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='cycle_on_days',
            field=models.PositiveIntegerField(blank=True, help_text='Active days per cycle (e.g. 5 for 5-on/2-off). Leave blank to disable cycling.', null=True),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='cycle_reference_date',
            field=models.DateField(blank=True, help_text='Day 1 of the first cycle. Defaults to item creation date if cycling is enabled.', null=True),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='doses_per_recurrence',
            field=models.PositiveIntegerField(default=1, help_text='Number of equally-spaced doses per recurrence period (e.g. 2 = morning + evening).'),
        ),
    ]
