# Generated by Django 5.2.4 on 2026-03-07 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0042_compound_bindingdb_id'),
        ('stacks', '0012_stackitem_cycling_multidose'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundTaxonomyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=60)),
                ('sub_id', models.CharField(db_index=True, max_length=60)),
                ('group_label', models.CharField(blank=True, max_length=120)),
                ('sub_label', models.CharField(blank=True, max_length=120)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_tags', to='compounds.compound')),
            ],
            options={
                'indexes': [models.Index(fields=['sub_id'], name='ctt_sub_idx'), models.Index(fields=['group_id'], name='ctt_grp_idx')],
                'unique_together': {('compound', 'sub_id')},
            },
        ),
    ]
